### ISSUE TITLE
Issues not found if no project is selected

### ISSUE THREAD

**Issue by paulkre** [jkraemer/stopwatch#3] opened 2020-08-13 00:32 UTC
Great plugin! This really puts Redmine on another level. Unfortunately the issue search field in the "Log Time" Dialoge is not working if no project is selected.

## Steps to reproduce

1. Make sure you are on the home page
2. Click on "Log Time" in the top right
3. Try to find an issue by typing its name in the search field

**Comment by jkraemer** [comment] 2020-08-19 00:02
hi, thanks for the feedback :) what version of Redmine are you using?

**Comment by jkraemer** [comment] 2021-10-05 03:38
closing, cannot reproduce.

**Closed as completed by jkraemer** 2021-10-05 03:38 UTC
